tags_ifnotequal.go
The proper end tag in Django for {%ifnotequal%} should be {%endifnotequal%}. We can see this reflected in the official [Django repo](https://github.com/django/django/blob/8047e3666b0b50bb04e6f16c2a4fb21ddfd5713f/tests/template_tests/syntax_tests/test_if_equal.py#L199). This pull request changes the tag to reflect this.
=> Proper tagging for ifnotequal

tags_for.go, template_tests/filters-execution.err, template_tests/filters-execution.err.out
When we return nil, we override non-nil value set to `forError` while processing for loop body. Here is the fix and a test
=> Fix hiding error on processing for tag body

template_tests/if.tpl, template_tests/if.tpl.out, value.go
Tag **if** with negation works incorrectly if it is used to struct.
```go
package main
import (
"fmt"
"github.com/flosch/pongo2"
)
type Foo struct{
Bar string
}
func main() {
template := "{% if not Foo %}Foo not exists{% endif %} {% if not Bar %}Bar not exists{% endif %}"
context := pongo2.Context{
"Foo": Foo{
Bar: "bar",
},
}
tpl, _ := pongo2.FromString(template)
res, _ := tpl.Execute(context)
fmt.Println(res)
}
```
returns
```
Foo not exists Bar not exists
```
I thinks that was not done 013bfa474354404c86f7efb8facf725ec0614b39 (fixed **func IsTrue**, but ignored **func Negate**).
I used commit a269242022ae534b052672d6a9326a40560a63e7 and fixed this bug in pull request.
=> Expression does not work properly

README.md
I pulled together a small utility which implements the same semantics as the `j2` utility for Python, but using the pongo2 engine (and compiling to a much simpler deployment).
=> Add p2cli to the 3rd party utilities list.

lexer.go, parser.go, tags_comment.go, template_tests/comment.tpl, template_tests/comment.tpl.out
Currently contents of comments are being parsed as opposed to just lexed, so things like invalid tokens will break rendering of the page.  This pull prevents any parsing of content inside comments for both character and contextual validity.  Fixes #119 .
With plenty of tests!
=> Prevent content inside comments from being parsed in any way.

filters_builtin.go, template_tests/filters.tpl, template_tests/filters.tpl.out
Provides the inverse of join. This has been a notable missing feature against the join filter.
=> Add split filter builtin.

pongo2_template_test.go, template_sets.go
Added a way to go from bytes (which may come from a cache system, or the network), to templates, without having to convert to a string (which is then converted back to bytes).
=> Add FromBytes

pongo2_test.go, variable.go
When calling out of templates to functions in go, it's often times useful to be able to access the *ExecutionContext of the template. Rather than forcing all functions to take this argument, it's best just to perform a quick check to see if the function wants the context, and add if it does.
=> Add implicit *ExecutionContext arg for function calls

context.go, error.go, filters.go, filters_builtin.go, lexer.go, parser.go, tags_ssi.go, template.go, template_sets.go
It is a **breaking** change, so please review it carefully.
In most cases, it is useful to get the original error value returns from pongo2 to be able to handle it properly.
One more problem, I read pongo2 codes and see many panic usages should be replaced by returning error value, but it will be a drastically change, so I don't do it in this PR.
=> changes custom error type to include original error

lexer.go, template_tests/quotes.tpl, template_tests/quotes.tpl.out
Adding support for single quotes to allow inclusion of templates in the json files or in other places where we have to use double quotes or nested double quotes.
For example in this case where value is a string representing json
```
{
"key": "\"{{'hello'}}\""
}
```
Or makes it easier to read in cases where double quotes have been already used:
`val := "{{'hello'}}"`
=> Adding support for single quotes in variables, functions and tags

filters.go
The docs say that filters should be registered in the init. I had a use-case where I have a generator function produce filters so I need to check whether a filter exists before registering it.
=> Add ability to check if a filter exists

README.md
The pongo2gin repository has been moved from Github to Gitlab.
Also it has been moved into an organisation "go-box" on Gitlab.
=> Update pongo2gin link in README.md

template_sets.go
There is a scenario: since some templates are updated, the user want to reload the template file for `TemplateSet.FromCache()` without restarting the program.
So the user maybe empty the whole template cache, then `TemplateSet.FromCache()` can reload the modified template files automatically.
=> feat: allow the user to clean the template cache

parser_expression.go
I have a function that checks permissions and takes user as an argument. Because functions cannot be called with `nil` arguments for some reason, I must first check user:
`{% if user and HasPermissions(user) %}`
As this was implemented now `and` did not help because both sides were evaluated.
This should behave as all programming languages and only evaluate left side when other side is not necessary.
=> Only execute right side of or/and when necessary

.gitattributes, .gitignore, .travis.yml, AUTHORS, go.mod, pongo2_template_test.go, pongo2_test.go
1. Enable Golang Modules (https://github.com/golang/go/wiki/Modules) for better portability and to get rid of the weird vendors etc. folder structures
2. Make tests platform independent (no running on Linux, MacOS and Windows) - this includes line endings to always `lf`
3. Use sub-Runs in tests instead of Logf for better visibility if something happens
4. `go fmt` changed files
=> Enable Golang Modules (https://github.com/golang/go/wiki/Modules)

template_sets.go
Django supports loading templates from [multiple template backends](https://docs.djangoproject.com/en/dev/ref/settings/#std:setting-TEMPLATES). I had a need for similar behavior, and these changes work pretty well for me so far.
=> Add support for multiple template loaders

go.mod
This is an untagged commit ID, so the version should start with "v0.0.0" instead of "v1.0.0".
Fixes #214
=> Fix github.com/go-check/check version number

README.md
stopgap fix for #226 - Add an archive.org cached copy of the django 1.7 as it appears they are no longer directly available.
=> Issue #226 - Add link to cached version of missing 1.7 django docs

template_tests/if.tpl, template_tests/if.tpl.out, value.go
It allows to make it work with different but equivalent types (e.g. int and int64).
=> implement the "in" operator on slice with EqualValueTo()

docs/filters.md, filters_builtin.go, template_tests/filters.tpl, template_tests/filters.tpl.out
Jinja2 has filter `e` which is an alias of `escape`, it's shorter and easier to write. Hope we can have it too in pongo2. :)
FYI: https://jinja.palletsprojects.com/en/2.11.x/templates/#escape
=> Add filter `e` (alias of `escape`)

README.md
More info is here: https://github.com/dieselburner/pongo2gcloud
Documentation: https://pkg.go.dev/github.com/dieselburner/pongo2gcloud
=> readme: add pongo2gcloud 3rd-party package

pongo2_template_test.go, template.go, template_tests/block_render/deep.tpl, template_tests/block_render/deep.tpl.out, template_tests/inheritance/base3.tpl, template_tests/inheritance/inheritance3/skeleton.tpl
The efficiency of `ExecuteBlocks` was pretty poor. This improves it by:
- Only visiting the parent if it has a block that is being sought after
- When we first try to render a block in a template, rather then when we first visit the template
- Assign the buffer
- Assign the context
The results were pretty staggering, specifically when passing an empty block array, or when working on deeply nested inheritance.
```
// When passing empty blocks
// Original
BenchmarkExecuteBlocksWithEmptyBlocksSandboxActive-6   	  675499	      1746 ns/op	     952 B/op	       9 allocs/op
// New
BenchmarkExecuteBlocksWithEmptyBlocksSandboxActive-6   	26332879	        44.17 ns/op	      48 B/op	       1 allocs/op
// When passing blocks
// Original
BenchmarkExecuteBlocksWithoutSandbox-6   	  687286	      1792 …
```
=> Improve ExecuteBlocks performance.

tags_block.go, template_tests/extends_super3.tpl, template_tests/extends_super3.tpl.out, template_tests/extends_super4.tpl, template_tests/extends_super4.tpl.out, template_tests/inheritance/base4.tpl
This PR changes the `block.Super` output. Because the output content should not be escaped.
The `block.Super` in the current implementation returns an escaped content. Please see the following example.
layout.tpl
```
{% block content %}<h1>Title</h1>{% endblock %}
```
page.tpl
```
{% extends "layout.tpl" %}
{% block content %}
{{ block.Super }}
<p>page contents</p>
{% endblock %}
```
These templates output the following content.
```
&lt;h1&gt;Title&lt;/h1&gt;
<p>page contents</p>
```
But it is not the same behavior as Django template. The Django official document (https://django.readthedocs.io/en/1.7.x/topics/templates.html) says the following.
> Data inserted using {{ block.super }} will not be automatically escaped (see the next section), since it was already escaped, if necessary, in …
=> should not escape `block.Super`
